version: 0.2
env:
  variables:
    GRADLE: "/root/gradle-3.5/bin"

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - gradle build
  post_build:
    commands:
      - gradle -v
artifacts:
  files:
    - build/libs/*.jar
    - scripts/*.sh
    - appspec.yml
  #com/mycompany/app/HelloWorld.java, specifying yes will place this file in /HelloWorld.java
  discard-paths: yes
